# Generated by Django 4.1 on 2022-10-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
